// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFavYEP7aur1H9Mz1BTMxhahuUy0OQoB4',
    appId: '1:418710774460:web:f25564d8c429b8797f66b9',
    messagingSenderId: '418710774460',
    projectId: 'chatapp-6e2eb',
    authDomain: 'chatapp-6e2eb.firebaseapp.com',
    storageBucket: 'chatapp-6e2eb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1lwmsHXFFs92NyayteDF6JRNSY5GF3DE',
    appId: '1:418710774460:android:46d7f1e4dca969217f66b9',
    messagingSenderId: '418710774460',
    projectId: 'chatapp-6e2eb',
    storageBucket: 'chatapp-6e2eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4XnF2ZIvY-I21_yOcU5JEWxaJuzBcitY',
    appId: '1:418710774460:ios:88a1a36eb81a07527f66b9',
    messagingSenderId: '418710774460',
    projectId: 'chatapp-6e2eb',
    storageBucket: 'chatapp-6e2eb.appspot.com',
    iosBundleId: 'com.example.chatZone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4XnF2ZIvY-I21_yOcU5JEWxaJuzBcitY',
    appId: '1:418710774460:ios:88a1a36eb81a07527f66b9',
    messagingSenderId: '418710774460',
    projectId: 'chatapp-6e2eb',
    storageBucket: 'chatapp-6e2eb.appspot.com',
    iosBundleId: 'com.example.chatZone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFavYEP7aur1H9Mz1BTMxhahuUy0OQoB4',
    appId: '1:418710774460:web:684e839abc0444ff7f66b9',
    messagingSenderId: '418710774460',
    projectId: 'chatapp-6e2eb',
    authDomain: 'chatapp-6e2eb.firebaseapp.com',
    storageBucket: 'chatapp-6e2eb.appspot.com',
  );
}
